apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi 
        image: 492554570964.dkr.ecr.ap-northeast-2.amazonaws.com/fastapi:3

        ports:
        - containerPort: 8000
